### PR TITLE
MGMT-16687 Use additional partition for /var/lib/containers

### PR DESCRIPTION
**Pull request by javipolo**

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
@javipolo note that [4.15.2](https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.15.2) is available and have this fix:
[MGMT-16980](https://issues.redhat.com/browse/MGMT-16980): Change the default value of ENABLE_SKIP_MCO_REBOOT to false ([#6005](https://github.com/openshift/assisted-service/pull/6005)) #6005 
So please update the default target version and set the default behavior for preaching to use the additional partition.

**Comment by javipolo** [comment]
> Please update the default target version and set the default behavior for preaching to use the additional partition.

Done

I also added the ability to select whether to use the partition or directory method for preaching with an environment variable, defaulting to partition :)

I separated it in a different commit so it's easy to review the new changes
https://github.com/rh-ecosystem-edge/ib-orchestrate-vm/pull/39/commits/b7d434e9689afc70ff85436798bcda7732d52ac4

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Pull request merged**
