### PR TITLE
Fix markdown lists with codeblocks

### PR DESCRIPTION
**Pull request by javipolo**
/cc @eranco74 
/cc @omertuc

### CODE REVIEW

**Comment by omertuc** [comment]
I don't like that, why? It's nice to be able to specify the language syntax

**Comment by javipolo** [comment]
> I don't like that, why? It's nice to be able to specify the language syntax

When using a CLI tool to render markdown I discovered that not putting a blank line after the list item was not standard markdown. Then I noticed that numbered lists were not even being detected as lists:

Check and see that there are two items number 3
https://github.com/rh-ecosystem-edge/ib-orchestrate-vm/blob/master/README.ibi.md

So this PR makes that we comply with markdown syntax

I was also shocked that you cannot specify the type of syntax when doing it this way

Anyway, I don't have a strong opinion on either of the ways, if you prefer to leave the broken numbered lists in favor of better syntax highlighting, so be it :)

**Comment by javipolo** [comment]
> You're mentioning two issues (blank line after list item, numbered lists not being detected as lists) but you didn't mention what triple-back-tick vs indentation for codeblocking (which is what I care about) has to do with it

indentation codeblocks are the default in markdown
triple-back-tick code blocks are called fenced codeblocks

Markdown only supports fenced codeblocks at the root level, meaning they cannot be nested inside of a list
And so, when adding fenced codeblocks in the middle of a list, they "break" the list

In the case of numbered lists, it is obvious because the broken automatic numbering of items makes it visible

Indented codeblocks can be nested, so by changing to that codeblocks, the lists are not broken

I see three options here:
1. Use indented codeblocks when they need to be nested
2. Only use indented codeblocks when there is a numbered list. We will have syntax highlighting everywhere but in ordered lists
3. Dont use indented codeblocks, and write numbers manually the numbered lists

Since I don't have such a strong preference for any of those, I'd say we can go for options 2 or 3
You seem to have a stronger opinion on the issue, so tell me your preference and I'll amend this PR with that in mind

**Comment by omertuc** [comment]
Lol my opinion is not strong, it's just markdown syntax :laughing:. I'm just trying to understand what's going on. People often mistake my questions for opinions.

Anyway, option 3 is my favorite

**Comment by javipolo** [comment]
> Lol my opinion is not strong, it's just markdown syntax 😆. I'm just trying to understand what's going on. People often mistake my questions for opinions.

Sorry for the misunderstanding :D :D 

> Anyway, option 3 is my favorite

I just updated the markdowns to do that, please check it out

**Pull request merged**
